### ISSUE TITLE
Error compilando en Ubuntu 14.04

### ISSUE THREAD

**Issue by elpagano3** [bigdata-mx/factura-electronica#136]
Hola,

Cuando intento compilar cfdi-base 0.2.6-SNAPSHOT en linea de comandos en Ubuntu con:
Version JAVA: 1.8.0_66
Maven version: 3.0.5

Obtengo este error: 

[INFO] ------------------------------------------------------------------------
[INFO] Building cfdi-base 0.2.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ cfdi-base ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (copy-resources) @ cfdi-base ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.2:xjc (schema1-xjc) @ cfdi-base ---
[INFO] Ignored given or default xjbSources [/home/binary/install/factura/src/main/xjb], since it is not an existent file or directory.
[INFO] Ignored given or default sources [/home/binary/install/factura/src/main/xsd], since it is not an existent file or directory.
[WARNING] No XSD files found. Please check your plugin configuration.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.619s
[INFO] Finished at: Tue Jan 19 17:35:15 EST 2016
[INFO] Final Memory: 12M/112M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.2:xjc (schema1-xjc) on project cfdi-base: MojoExecutionException: NoSchemasException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.2:xjc (schema1-xjc) on project cfdi-base: 
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: 
        at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution(AbstractJavaGeneratorMojo.java:479)
        at org.codehaus.mojo.jaxb2.AbstractJaxbMojo.execute(AbstractJaxbMojo.java:257)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.codehaus.mojo.jaxb2.NoSchemasException
        at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.getXjcArguments(AbstractJavaGeneratorMojo.java:591)
        at org.codehaus.mojo.jaxb2.javageneration.AbstractJavaGeneratorMojo.performExecution(AbstractJavaGeneratorMojo.java:385)
        ... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Agradezco su ayuda.

**Comment by hortegag91** [comment]
El problema es que jaxb en la versión de java 8 tiene ciertas diferencias.
Si pones un poco de atención en el error, te marca un archivo faltante.
`[INFO] Ignored given or default xjbSources [/home/binary/install/factura/src/main/xjb], since it is not an existent file or directory.
[INFO] Ignored given or default sources [/home/binary/install/factura/src/main/xsd], since it is not an existent file or directory.
[WARNING] No XSD files found. Please check your plugin configuration.`
Tienes que colocar los archivos correspondientes en esta ruta, o actualizar tu archivo POM para que busque en la ruta correcta.
