### ISSUE TITLE
Error al intentar leer la llave

### ISSUE THREAD

**Issue by luisgithub** [bigdata-mx/factura-electronica#190]
Hola alguien me pudiera ayudar, desde que hice le upgrade de la libreria 2.5 a la 3.3 no puedo leer la llave, mi codigo es el siguiente:

            PrivateKey privateKey = KeyLoaderFactory.createInstance(KeyLoaderEnumeration.PRIVATE_KEY_LOADER, new FileInputStream(pathToKey), keypass).getKey();
            PublicKeyLoader publicKeyLoader = new PublicKeyLoader(pathToCer);
            X509Certificate publicKey = publicKeyLoader.getKey();
            //Create comprobante
            Comprobante comprobante = createComprobante(venta);

y el error que obtengo al intentar leer la llave es el siguiente:

java.lang.ClassNotFoundException: org.apache.commons.ssl.PKCS8Key
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
	at mx.bigdata.sat.security.PrivateKeyLoader.extractProtectedPrivateKey(PrivateKeyLoader.java:89) ~[cfdi-base-0.3.0.jar:na]
	at mx.bigdata.sat.security.PrivateKeyLoader.setPrivateKey(PrivateKeyLoader.java:67) ~[cfdi-base-0.3.0.jar:na]
	at mx.bigdata.sat.security.PrivateKeyLoader.<init>(PrivateKeyLoader.java:34) ~[cfdi-base-0.3.0.jar:na]
	at mx.bigdata.sat.security.factory.KeyLoaderFactory.createInstance(KeyLoaderFactory.java:35) ~[cfdi-base-0.3.0.jar:na]
	at com.erpsom.service.VentaService.crearCFD(VentaService.java:103) ~[classes/:na]

alguna sugerencia?

**Comment by OswaldoJaimeSolis** [comment]
Solo actualiza a la versión mas nueva 
https://mvnrepository.com/artifact/org.apache.commons.ssl/not-yet-commons-ssl/0.3.11-redhat-2
